/**
 * Mock Opportunities Data
 * 8 realistic test opportunities spread across the Yaoundé area
 * Used when Firebase is not configured (demo mode)
 */

const now = Date.now();

export const MOCK_OPPORTUNITIES = [
  // ── AGRICULTURE ──────────────────────────────────────────────
  {
    id: 'mock-agri-001',
    title: 'Farm Assistants – Cocoa Processing',
    description:
      'We are looking for 10 experienced farm assistants to help with cocoa harvesting and processing during peak season. Must be physically fit and available for seasonal work.',
    category: 'agriculture',
    location: {
      latitude: 3.848,
      longitude: 11.5021,
      address: 'Mbalmayo Processing Facility',
      geohash: 's0gs3d',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
        village: 'Mbalmayo',
      },
    },
    organizationId: 'coop_001',
    organizationName: 'Mbalmayo Cocoa Cooperative',
    organizationType: 'cooperative',
    contactInfo: {
      name: 'Jean Paul Nkomo',
      phone: '+237672345678',
      whatsapp: '+237672345678',
      email: 'coop@example.com',
    },
    jobDetails: {
      vacancies: 10,
      skillLevel: 'unskilled',
      requiredSkills: [],
      experience: 0,
      certificates: [],
    },
    compensation: {
      currency: 'FCFA',
      dailyRate: 4500,
      monthlyRate: null,
      totalBudget: 1350000,
    },
    duration: {
      type: 'seasonal',
      startDate: new Date('2025-07-01').getTime(),
      endDate: new Date('2025-12-31').getTime(),
      daysPerWeek: 5,
      hoursPerDay: 8,
    },
    sectorDetails: { commodity: 'cocoa', processingCapacity: '500kg/day' },
    support: { ppe_provided: false, accommodation: true, meals: true, transport: true },
    status: 'open',
    featured: true,
    rating: { average: 4.7, count: 23 },
    createdAt: now - 86400000 * 2,
    updatedAt: now - 86400000 * 2,
  },

  {
    id: 'mock-agri-002',
    title: 'Grain Harvesters Needed',
    description:
      'Looking for 15 grain harvesters for the harvest season. Experience with combine harvesters preferred but not required.',
    category: 'agriculture',
    location: {
      latitude: 3.87,
      longitude: 11.53,
      address: 'Ekounou Grain Depot',
      geohash: 's0gs7e',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
        village: 'Ekounou',
      },
    },
    organizationId: 'coop_002',
    organizationName: 'Ekounou Grain Cooperative',
    organizationType: 'cooperative',
    contactInfo: {
      name: 'Amara Fru',
      phone: '+237678912345',
      whatsapp: '+237678912345',
      email: 'grain@example.com',
    },
    jobDetails: {
      vacancies: 15,
      skillLevel: 'semi-skilled',
      requiredSkills: ['harvesting'],
      experience: 1,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 5000, monthlyRate: null, totalBudget: 1875000 },
    duration: {
      type: 'seasonal',
      startDate: new Date('2025-08-15').getTime(),
      endDate: new Date('2025-10-31').getTime(),
      daysPerWeek: 6,
      hoursPerDay: 8,
    },
    sectorDetails: { commodity: 'grain', processingCapacity: '200 bags/day' },
    support: { ppe_provided: true, accommodation: false, meals: true, transport: false },
    status: 'open',
    featured: false,
    rating: { average: 4.3, count: 12 },
    createdAt: now - 86400000 * 5,
    updatedAt: now - 86400000 * 5,
  },

  // ── CONSTRUCTION ─────────────────────────────────────────────
  {
    id: 'mock-const-001',
    title: 'Masons Needed – Residential Complex',
    description:
      'Seeking experienced masons for foundation and wall construction on a new residential complex. Must have 2+ years experience with documentation.',
    category: 'construction',
    location: {
      latitude: 3.862,
      longitude: 11.506,
      address: 'Chantier Résidentiel K7, Yaoundé',
      geohash: 's0gs3f',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'const_001',
    organizationName: 'Chantier Résidentiel K7',
    organizationType: 'contractor',
    contactInfo: {
      name: 'Mr. Samba Diallo',
      phone: '+237691234567',
      whatsapp: '+237691234567',
      email: 'chantier.k7@example.com',
    },
    jobDetails: {
      vacancies: 12,
      skillLevel: 'skilled',
      requiredSkills: ['masonry', 'wall-construction'],
      experience: 2,
      certificates: ['TVET Masonry Certificate'],
    },
    compensation: { currency: 'FCFA', dailyRate: 7000, monthlyRate: null, totalBudget: 4200000 },
    duration: {
      type: 'temporary',
      startDate: new Date('2025-06-15').getTime(),
      endDate: new Date('2025-09-30').getTime(),
      daysPerWeek: 5,
      hoursPerDay: 8,
    },
    sectorDetails: { projectType: 'building', currentPhase: 'foundation', safetyCompliant: true },
    support: { ppe_provided: true, accommodation: false, meals: false, transport: true },
    status: 'open',
    featured: true,
    rating: { average: 4.5, count: 18 },
    createdAt: now - 86400000 * 1,
    updatedAt: now - 86400000 * 1,
  },

  {
    id: 'mock-const-002',
    title: 'General Laborers – Road Construction',
    description:
      'RN4 Highway rehabilitation project needs 35 general laborers for earthworks and site preparation. No experience needed, training provided.',
    category: 'construction',
    location: {
      latitude: 3.82,
      longitude: 11.54,
      address: 'Route Nationale RN4-Est',
      geohash: 's0gr8a',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'const_002',
    organizationName: 'Road Authority – RN4 Project',
    organizationType: 'contractor',
    contactInfo: {
      name: 'Eng. Jean Baptiste',
      phone: '+237695678901',
      whatsapp: '+237695678901',
      email: 'rn4.project@example.com',
    },
    jobDetails: {
      vacancies: 35,
      skillLevel: 'unskilled',
      requiredSkills: [],
      experience: 0,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 3500, monthlyRate: null, totalBudget: 3150000 },
    duration: {
      type: 'temporary',
      startDate: new Date('2025-05-01').getTime(),
      endDate: new Date('2025-11-30').getTime(),
      daysPerWeek: 6,
      hoursPerDay: 8,
    },
    sectorDetails: { projectType: 'road', currentPhase: 'earthworks', safetyCompliant: true },
    support: { ppe_provided: true, accommodation: false, meals: true, transport: true },
    status: 'open',
    featured: false,
    rating: { average: 4.1, count: 45 },
    createdAt: now - 86400000 * 10,
    updatedAt: now - 86400000 * 10,
  },

  // ── SERVICES ─────────────────────────────────────────────────
  {
    id: 'mock-serv-001',
    title: 'Tailoring Workshop – Apprentice Wanted',
    description:
      'Modern tailoring workshop seeking apprentice to learn design and cutting. 2-year program with monthly stipend after probation.',
    category: 'services',
    location: {
      latitude: 3.855,
      longitude: 11.51,
      address: 'Marché Central, Yaoundé',
      geohash: 's0gs3h',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'bus_001',
    organizationName: 'Atelier Couture Aminata',
    organizationType: 'business',
    contactInfo: {
      name: 'Aminata Diop',
      phone: '+237678123456',
      whatsapp: '+237678123456',
      email: 'aminata.couture@example.com',
    },
    jobDetails: {
      vacancies: 2,
      skillLevel: 'unskilled',
      requiredSkills: [],
      experience: 0,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 0, monthlyRate: 50000, totalBudget: 1200000 },
    duration: {
      type: 'permanent',
      startDate: new Date('2025-07-01').getTime(),
      endDate: new Date('2027-07-01').getTime(),
      daysPerWeek: 5,
      hoursPerDay: 8,
    },
    sectorDetails: { serviceCategory: 'tailoring', apprenticeshipAvailable: true },
    support: { ppe_provided: false, accommodation: false, meals: false, transport: false },
    status: 'open',
    featured: false,
    rating: { average: 4.8, count: 12 },
    createdAt: now - 86400000 * 3,
    updatedAt: now - 86400000 * 3,
  },

  {
    id: 'mock-serv-002',
    title: 'Electronics Repair – Assistant Needed',
    description:
      'Electronics repair shop looking for a tech-savvy assistant. Opportunity to learn phone and computer repair. Walk-ins welcome.',
    category: 'services',
    location: {
      latitude: 3.86,
      longitude: 11.515,
      address: 'Yaoundé Downtown Tech Market',
      geohash: 's0gs3g',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'bus_002',
    organizationName: 'Réparation Électronique – TechFix',
    organizationType: 'business',
    contactInfo: {
      name: 'Martin Obi',
      phone: '+237690234567',
      whatsapp: '+237690234567',
      email: 'martin.techfix@example.com',
    },
    jobDetails: {
      vacancies: 1,
      skillLevel: 'semi-skilled',
      requiredSkills: ['electronics-basics', 'customer-service'],
      experience: 0,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 3000, monthlyRate: null, totalBudget: 360000 },
    duration: {
      type: 'permanent',
      startDate: new Date('2025-06-01').getTime(),
      endDate: null,
      daysPerWeek: 6,
      hoursPerDay: 8,
    },
    sectorDetails: { serviceCategory: 'repair', apprenticeshipAvailable: true },
    support: { ppe_provided: false, accommodation: false, meals: false, transport: false },
    status: 'open',
    featured: false,
    rating: { average: 4.6, count: 8 },
    createdAt: now - 86400000 * 7,
    updatedAt: now - 86400000 * 7,
  },

  // ── STATE / HIMO ─────────────────────────────────────────────
  {
    id: 'mock-state-001',
    title: 'HIMO – Canal Irrigation Zone 3',
    description:
      'Government irrigation canal rehabilitation project. Open to local youth ages 18-35. No experience needed, all training provided on-site.',
    category: 'state',
    location: {
      latitude: 3.83,
      longitude: 11.48,
      address: 'Commune Centre-Sud Irrigation Zone 3',
      geohash: 's0gr9b',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'gov_001',
    organizationName: 'Ministry of Water & Forestry',
    organizationType: 'government',
    contactInfo: {
      name: 'Mr. Fonkwo',
      phone: '+237222123456',
      whatsapp: '+237222123456',
      email: 'minwa.recruitment@example.com',
    },
    jobDetails: {
      vacancies: 60,
      skillLevel: 'unskilled',
      requiredSkills: [],
      experience: 0,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 3500, monthlyRate: null, totalBudget: 8400000 },
    duration: {
      type: 'temporary',
      startDate: new Date('2025-07-01').getTime(),
      endDate: new Date('2025-09-15').getTime(),
      daysPerWeek: 5,
      hoursPerDay: 8,
    },
    sectorDetails: { projectType: 'irrigation', currentPhase: 'excavation' },
    support: { ppe_provided: true, accommodation: false, meals: true, transport: true },
    status: 'open',
    featured: true,
    rating: { average: 4.2, count: 156 },
    createdAt: now - 86400000 * 4,
    updatedAt: now - 86400000 * 4,
  },

  // ── TRAINING ─────────────────────────────────────────────────
  {
    id: 'mock-train-001',
    title: 'Free Digital Skills Bootcamp',
    description:
      '6-week intensive bootcamp covering web development, mobile app basics, and digital marketing. Laptops provided. Certificate awarded on completion.',
    category: 'training',
    location: {
      latitude: 3.845,
      longitude: 11.495,
      address: 'Centre Multifonctionnel de Yaoundé',
      geohash: 's0gs2k',
      administrativeLevel: {
        region: 'Centre',
        division: 'Mfoundi',
        commune: 'Yaoundé',
      },
    },
    organizationId: 'ngo_001',
    organizationName: 'YouthTech Cameroon',
    organizationType: 'ngo',
    contactInfo: {
      name: 'Dr. Estelle Manga',
      phone: '+237699876543',
      whatsapp: '+237699876543',
      email: 'info@youthtech.cm',
    },
    jobDetails: {
      vacancies: 30,
      skillLevel: 'unskilled',
      requiredSkills: [],
      experience: 0,
      certificates: [],
    },
    compensation: { currency: 'FCFA', dailyRate: 0, monthlyRate: 25000, totalBudget: 750000 },
    duration: {
      type: 'temporary',
      startDate: new Date('2025-07-15').getTime(),
      endDate: new Date('2025-08-31').getTime(),
      daysPerWeek: 5,
      hoursPerDay: 6,
    },
    sectorDetails: { serviceCategory: 'digital-skills', apprenticeshipAvailable: false },
    support: { ppe_provided: false, accommodation: false, meals: true, transport: false },
    status: 'open',
    featured: true,
    rating: { average: 4.9, count: 67 },
    createdAt: now - 86400000 * 1,
    updatedAt: now - 86400000 * 1,
  },
];
